version: "3.7"
services:
  db_mysql:
    build:
      context: ./mysql
      dockerfile: ./mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_USER: admin
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_DATABASE: app_messages
      TZ: Asia/Seoul
    secrets:
      - mysql_secret
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

secrets:
  mysql_secret:
    file: mysql_secret

volumes:
  mysql_data:
